app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('inicio', function () {
    return view('welcome');
});
Route::group(['prefix' => 'admin', 'middleware'=>'auth'], function() {
    Route::resource('user', 'UserController');
    Route::get('user/{id}/destroy',
    	[
    		"uses"	=>	"UserController@destroy",
    		"as"	=>	"admin.user.destroy"
    	]);

    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/destroy',[
    		'uses'	=>	'CategoryController@destroy',
    		'as'	=>	'admin.category.destroy'
    	]);
    Route::resource('tags', 'TagsController');
    Route::get('tags/{id}/destroy',[
            'uses'  =>  'TagsController@destroy',
            'as'    =>  'admin.tags.destroy'
        ]);
    Route::resource('article', 'ArticleController');
    Route::get('article/{id}/destroy',[
            'uses'  =>  'ArticleController@destroy',
            'as'    =>  'admin.article.destroy'
        ]);

});

Route::auth();

Route::get('/', 'HomeController@index');

resources/views/admin/template/parts/nav.blade.php
<div class="container">
	<div class="row">
	<div class="col-md-12">
	
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Inicio</a>
	    </div>

	   
	    
	    

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	     @if (Auth::user())
			      <ul class="nav navbar-nav">
			        <li class=""><a href="{{ route('admin.user.index') }}">Usuarios <span class="sr-only">(current)</span></a></li>
			        <li><a href="{{ route('admin.category.index') }}">Categorias</a></li>
			        <li><a href="{{ route('admin.article.index') }}">Articulos</a></li>
			        <li><a href="#">Imagenes</a></li>
			        <li><a href="{{route('admin.tags.index')}}">Tags</a></li>
			        <!--<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="#">One more separated link</a></li>
			          </ul>
			        </li>-->
			      </ul>
			      <!--<form class="navbar-form navbar-left" role="search">
			        <div class="form-group">
			          <input type="text" class="form-control" placeholder="Search">
			        </div>
			        <button type="submit" class="btn btn-default">Submit</button>
			      </form>-->
	      @endif

	      <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	</div>
	</div>
	</div>