app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('inicio', function () {
    return view('welcome');
});
Route::group(['prefix' => 'admin', 'middleware'=>'auth'], function() {
    Route::resource('user', 'UserController');
    Route::get('user/{id}/destroy',
    	[
    		"uses"	=>	"UserController@destroy",
    		"as"	=>	"admin.user.destroy"
    	]);

    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/destroy',[
    		'uses'	=>	'CategoryController@destroy',
    		'as'	=>	'admin.category.destroy'
    	]);
    Route::resource('tags', 'TagsController');
    Route::get('tags/{id}/destroy',[
            'uses'  =>  'TagsController@destroy',
            'as'    =>  'admin.tags.destroy'
        ]);
    Route::resource('article', 'ArticleController');
    Route::get('article/{id}/destroy',[
            'uses'  =>  'ArticleController@destroy',
            'as'    =>  'admin.article.destroy'
        ]);

});

Route::auth();

Route::get('/', 'HomeController@index');

app/category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    protected $table='categories';
    protected $fillable = ['name'];

    public function articles()
    {
    	return $this->hasMany('App\article');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\category;

use Laracasts\Flash\Flash;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cat = category::orderBy('name', 'ASC')->paginate(6);
        return view('admin.categories.index')->with('cat', $cat);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cat = new category();
        $cat->name = $request->title;
        $cat->save();

        Flash::success('Se registro correctamente la categoria '.$cat->name);
        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cat = category::find($id);
        return view('admin.categories.edit')->with('cat', $cat);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = category::find($id);
        $cat->name = $request->title;
        $cat->save();

        Flash::info('Se actualizo correctamente');
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = category::find($id);
        $cat->delete();

        Flash::error('La categoria '.$cat->name.' se ha eliminado correctamente');
        return redirect()->route('admin.category.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.template.main');

@section('title')
	Categoria
@stop

@section('header')
	
@stop

@section('cabeceraArticle')
	<h4>Seccion de creacion de categoria</h4>
@stop

@section('cuerpoArticle')
	
	{!! Form::open(['route'=>'admin.category.store', 'method'=>'POST']) !!}

		<div class="form-group">
			{!! Form::label('title', 'Titulo', []) !!}
			{!! Form::text('title', null, ['class'=>'form-control', 'placeholder'=>'Ingrese el titulo', 'required'=>'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Enviar', ['class'=>'btn btn-primary']) !!}
		</div>

	{!! Form::close() !!}

@stop

resources/views/admin/categories/edit.blade.php
@extends('admin.template.main');

@section('title')
	Categoria Actualizar
@stop

@section('header')
	
@stop

@section('cabeceraArticle')
	<h4>Seccion de actializacion de categorias</h4>
@stop

@section('cuerpoArticle')
	
	{!! Form::open(['route'=>['admin.category.update', $cat], 'method'=>'PUT']) !!}

		<div class="form-group">
			{!! Form::label('title', 'Titulo', []) !!}
			{!! Form::text('title', $cat->name, ['class'=>'form-control', 'placeholder'=>'Ingrese el titulo', 'required'=>'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Actualizar', ['class'=>'btn btn-primary']) !!}
		</div>

	{!! Form::close() !!}

@stop

resources/views/admin/categories/index.blade.php
@extends('admin.template.main');

@section('title')
	Categoria
@stop

@section('header')
	
@stop

@section('cabeceraArticle')
	<h4>Seccion de listados de categoria</h4>
@stop

@section('cuerpoArticle')
	
	<div class="continer">
    	<a href="{{ route('admin.category.create') }}" class="btn btn-info">AGREGAR CATEGORIA</a>
    	
        <hr>
       	<table class="table table-hover table-striped">
    		<thead>
	    		<tr>
	    			<th>ID</th>
	    			<th>TITULO</th>
	    			<th>BORRAR</th>
                    <th>ACTUALIZAR</th>
	    		</tr>
    		</thead>
    		<tbody>
    			@foreach ($cat as $cate)
    				<tr>
    					<td>{{ $cate->id }}</td>
    					<td>{{ $cate->name }}</td>    					
    					<td>
    						<a class="btn btn-danger" href="{{ route('admin.category.destroy', $cate->id) }}" onclick="return confirm('Le vais a echar bolas ?')"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
    					</td>
                        <td>
                            <a class="btn btn-info" href="{{ route('admin.category.edit', $cate->id) }}"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>
    				    </td>
                    </tr>
					
    			@endforeach
    		</tbody>    		
    	</table>    
	<div class="pull-right">{!! $cat->render() !!}</div>

@stop